version: '3.8'
services:

  dvwa:
    image: vulnerables/web-dvwa:latest
    container_name: lab01-dvwa
    ports:
      - "8080:80"
    depends_on: [db]
    networks:
      labnet:
        ipv4_address: 192.168.101.10
    environment:
      DB_SERVER: db
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    restart: unless-stopped

  db:
    image: mysql:5.7
    container_name: lab01-db
    networks:
      labnet:
        ipv4_address: 192.168.101.20
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./splunk-config/seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro
    expose: ["3306"]
    restart: unless-stopped

  flask-api:
    build:
      context: ./flask-target
    container_name: lab01-flask
    ports:
      - "5000:5000"
    networks:
      labnet:
        ipv4_address: 192.168.101.30
    environment:
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
    restart: unless-stopped

  splunk:
    image: splunk/splunk:9.1.0
    container_name: lab01-splunk
    ports:
      - "8000:8000"
    networks:
      labnet:
        ipv4_address: 192.168.101.40
    environment:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD: ${SPLUNK_PASSWORD}
    volumes:
      - splunk_data:/opt/splunk/var
      - ./splunk-config/inputs.conf:/opt/splunk/etc/system/local/inputs.conf:ro
    restart: unless-stopped

  kali:
    image: kalilinux/kali-rolling:latest
    container_name: lab01-kali
    networks:
      labnet:
        ipv4_address: 192.168.101.5
    stdin_open: true
    tty: true
    command: sleep infinity
    restart: unless-stopped

networks:
  labnet:
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 192.168.101.0/24
          gateway: 192.168.101.1

volumes:
  db_data:
  splunk_data:
