services:
  web:
    build: .
    ports:
      - "${PORT_80:-8080}:80"
    environment:
      APP_NAME: "Banco HACKL4BS Vault"
      APP_ENV: ctf
      APP_DEBUG: "false"
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: reto
      DB_USER: reto_user
      DB_PASSWORD: reto_password
      INITIAL_BALANCE: 20000
      MAX_TRANSFER_AMOUNT: 100
      WINDOW_SECONDS: 60
      UNLOCK_DRIFT: 1200
      MIN_APPROVED_TRANSFERS: 8
      TRANSFER_DELAY_MIN_US: 80000
      TRANSFER_DELAY_MAX_US: 220000
      CTF_FLAG: ${FLAG}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:10.11
    environment:
      MARIADB_DATABASE: reto
      MARIADB_USER: reto_user
      MARIADB_PASSWORD: reto_password
      MARIADB_ROOT_PASSWORD: root_password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 3s
      retries: 20
